### PR TITLE
Fixes #695

### LINKED ISSUE #695: Exception when sending a constant to a channel with a defined channel type
The following program causes a violation during encoding:
```
type ChannelMsgType int

const ChannelMsg ChannelMsgType = 42

pred sendInvariant(v ChannelMsgType) {
    true
}

requires acc(channel.SendChannel(), 1/2)
requires channel.SendGivenPerm() == sendInvariant!<_!>
requires channel.SendGotPerm() == PredTrue!<!>
func sendMsg(channel chan ChannelMsgType) {
    fold sendInvariant!<_!>(ChannelMsg)
    fold PredTrue!<!>()
    assert acc(channel.SendChannel(), _) && sendInvariant!<_!>(ChannelMsg)
    assert acc(channel.SendChannel(), _) && channel.SendGivenPerm()(ChannelMsg)
    channel <- ChannelMsg
}
```

The channel encoding checks whether the message type is identical to the channel type. This is however not the case here because constant propagation replaces `ChannelMsg` with `42`, i.e., an integer literal.

### PR DESCRIPTION
**Pull request by ArquintL**
This PR fixes issue #695.

We drop the violation in the channel encoding as the type-checker is anyway more lenient and allows messages of types that are *assignable* (and not necessarily equal) to the channel type.
However, this change requires a small change to the channel encoding as we can no longer use the message's type when constructing the pure method calls to the channel's invariant getters (`SendGivenPerm`, `SendGotPerm`, `RecvGivenPerm`, and `RecvGotPerm`) but have to use the channel type instead (as they are not necessarily equal anymore).

### CODE REVIEW

**Comment by ArquintL** [comment]
I've observed a non-deterministic behavior of test case `same_package/import-fail01`. E.g., it failed in [this](https://github.com/viperproject/gobra/actions/runs/6661030283/job/18103206957) CI run.
However, I double-checked the corresponding Viper encoding, which does not change due to this PR's code changes.

File: src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala [hunk 1]
```diff
@@ -68,7 +67,7 @@ class ChannelEncoding extends LeafTypeEncoding {
           )
 
           // exhale [c].RecvGivenPerm()()
-          recvGivenPermInst = getChannelInvariantAccess(channel, recvGivenPerm, Vector())(exp.info)
+          recvGivenPermInst = getChannelInvariantAccess(channel, recvGivenPerm, Vector.empty, Vector.empty)(exp.info)
```
Comment (jcp19) [inline src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala:70]: using `Vector.empty` instead of `Vector()` sounds like a good idea! I wonder, does it actually save an allocation, or is there any specific optimisation for calling the constructor with an empty list?

**Review by jcp19 — APPROVED** [review]

File: src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala (hunk 1 above)
Comment (ArquintL) [reply src/main/scala/viper/gobra/translator/encodings/channels/ChannelEncoding.scala:70]: I've actually no idea. My motivation was to slightly help readability
