### PR TITLE
Fixes issue #411

### LINKED ISSUE #411: Chopper loses isolated node.
Chopper prints that an isolated node is lost in attached file.

[pkg1.txt](https://github.com/viperproject/gobra/files/8041868/pkg1.txt)

### PR DESCRIPTION
**Pull request by Felalolf**
Fixes #411. The problem was that dfs stopped when it found an already visited node.

### CODE REVIEW

File: src/main/scala/viper/gobra/util/ViperChopper.scala [hunk 1]
```diff
@@ -69,7 +69,7 @@ object ViperChopper {
       var forallSmallNode: (Int => Boolean) => Boolean = null // for the safety check
 
       val result = {
-        if (nodes.size < 10) {
+        if (nodes.size <= 2) {
```
Comment (jcp19) [inline src/main/scala/viper/gobra/util/ViperChopper.scala:72]: Won't this make it very unlikely to ever execute the non-SCC algorithm? If that is the case, I wonder if we should keep this algorithm that only kicks in in small programs

Comment (jcp19) [reply src/main/scala/viper/gobra/util/ViperChopper.scala:72]: Yes, you are right. Thanks!

**Review by ArquintL — APPROVED** [review]
