### PR TITLE
Fix bug 805

### LINKED ISSUE #805: Array Pointer Shorthand
> For a of pointer to array type: `a[x]` is shorthand for `(*a)[x]`   ([go spec](https://go.dev/ref/spec#Index_expressions))

This is currently not handled by Gobra and one must explicitly dereference the pointers.
The specs can get hard to read: 
```go
// @ preserves acc(&((*p)[0]))
// @ ensures (*p)[0] == 0
func dereferencing(p *[10]int) {
	(*p)[0] = 0
}
```
We should be able to write:
```go
// @ preserves acc(&p[0])
// @ ensures p[0] == 0
func shorthand(p *[10]int) {
	p[0] = 0
}
```

```text
15:18:02.095 [main] ERROR viper.gobra.GobraRunner$ - An assumption was violated during execution.
15:18:02.096 [main] ERROR viper.gobra.GobraRunner$ - Logic error: Expected slice, array, map, or sequence, but got *[10]int
viper.gobra.util.Violation$LogicException: Logic error: Expected slice, array, map, or sequence, but got *[10]int
```

For pointers to structs the indirection works:
```go
func structs() {
	p := new(struct{ value int })
	p.value = 1
	//@ assert p.value == 1
}
```

### PR DESCRIPTION
**Pull request by jcp19**
This PR fixes #805 by adding support for operations over pointers to arrays. In addition, it simplifies some code in neighboring parts of code that was unnecessarily complicated

### CODE REVIEW

File: src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala [hunk 1]
```diff
@@ -521,6 +525,10 @@ trait ExprTyping extends BaseTyping { this: TypeInfoImpl =>
     case PLength(op) => isExpr(op).out ++ {
       underlyingType(exprType(op)) match {
         case _: ArrayT | _: SliceT | _: GhostSliceT | StringT | _: VariadicT | _: MapT | _: MathMapT => noMessages
+        case ActualPointerT(_: ArrayT)  =>
+          // Go allows getting the length of a pointer to an array, but it does not allow obtaining the
+          // length of a pointer of a type T whose underlying slice is an array.
```
Comment (ArquintL) [inline src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala:530]:
```suggestion
          // Go allows getting the length of a pointer to an array, but it does not allow obtaining the
          // length of a pointer of type T, whose underlying type is an array.
```

File: src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala [hunk 2]
```diff
@@ -529,6 +537,10 @@ trait ExprTyping extends BaseTyping { this: TypeInfoImpl =>
     case PCapacity(op) => isExpr(op).out ++ {
       underlyingType(exprType(op)) match {
         case _: ArrayT | _: SliceT | _: GhostSliceT => noMessages
+        case ActualPointerT(_: ArrayT)  =>
+          // Go allows getting the capacity of a pointer to an array, but it does not allow obtaining the
+          // capacity of a pointer of a type T whose underlying slice is an array.
```
Comment (ArquintL) [inline src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala:542]:
```suggestion
          // Go allows getting the capacity of a pointer to an array, but it does not allow obtaining the
          // capacity of a pointer of a type T, whose underlying type is an array.
```

File: src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala [hunk 3]
```diff
@@ -529,6 +537,10 @@ trait ExprTyping extends BaseTyping { this: TypeInfoImpl =>
...
+        noMessages
```
Comment (ArquintL) [inline src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala:543]:
```suggestion
          noMessages
```

File: src/main/scala/viper/gobra/frontend/Desugar.scala [hunk 4]
```diff
@@ -2773,11 +2774,7 @@ object Desugar extends LazyLogging {
             dop <- go(op)
           } yield dop match {
             case dop : in.ArrayLit => in.IntLit(dop.length)(src)
```
Comment (ArquintL) [inline src/main/scala/viper/gobra/frontend/Desugar.scala:2776]: Is there a reason for specialcasing `ArrayLit` here? Given that you've extended the array encoding to support `cap`, it seems to me we could simply convert `PCapacity` to `Capacity`.
Furthermore, the same comment also applies to the lines above for the `PLength` case

**Review by ArquintL — APPROVED** [review]
I've some minor suggestions and a question

File: src/main/scala/viper/gobra/frontend/Desugar.scala (hunk 4 above)
Comment (jcp19) [reply src/main/scala/viper/gobra/frontend/Desugar.scala]: good point, I don't see immediately why you would do that, except for wanting to avoid a call to the length function, which may be useful in some cases to avoid introducing triggering terms (for the same reason, it may lead to confusing triggering behaviour, as a pattern that is expected to occur does not occur in the generated viper program). I have simplified this

File: src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala (hunk 1 above)
Comment (jcp19) [reply src/main/scala/viper/gobra/frontend/info/implementation/typing/ExprTyping.scala]: I agree with this suggestion, except for the comma before "whose", given that the clause introduced by whose is supposed to be restrictive. Putting the comma thus changes the meaning of the sentence

File: src/main/scala/viper/gobra/frontend/Desugar.scala (hunk 4 above)
Comment (jcp19) [reply src/main/scala/viper/gobra/frontend/Desugar.scala]: ah, this special case was prior to my changes. I removed the special case

Comment (ArquintL) [reply src/main/scala/viper/gobra/frontend/Desugar.scala]: Yes, I could have been clearer on this ^^
